# Generated by Django 5.1.6 on 2025-02-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproductmodel',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='service_management.servicetypemodel'),
        ),
    ]
