# Generated by Django 5.1.6 on 2025-02-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0002_alter_serviceproductmodel_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='product',
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='product',
            field=models.ManyToManyField(related_name='services', to='service_management.serviceproductmodel'),
        ),
    ]
