# Generated by Django 5.1.6 on 2025-02-21 23:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedspaModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=256)),
                ('email_address', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Medspa',
                'verbose_name_plural': 'Medspas',
            },
        ),
    ]
