# Generated by Django 5.1.6 on 2025-02-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentmodel_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
